/** One-click harmonious menu, brand text, and CTA button colors */

export const HEADER_BEAUTY_PALETTES = [
  {
    id: "md-brand",
    label: "MaatriDev teal",
    swatch: "linear-gradient(135deg, #007cc3, #00b8a9)",
    patch: {
      headerNavOnDark: "#ffffff",
      headerNavOnLight: "#1a2b3c",
      headerNavHoverColor: "#e0f2fe",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(0, 184, 169, 0.38)",
      headerBrandTextOnDark: "#ffffff",
      headerBrandSubtextOnDark: "rgba(224, 242, 254, 0.92)",
      headerBrandTextOnLight: "#0a1628",
      headerBrandSubtextOnLight: "rgba(26, 43, 60, 0.72)",
      headerCtaBg: "#007cc3",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#006aa8",
      headerCtaBorderColor: "#007cc3",
    },
  },
  {
    id: "ocean-glow",
    label: "Ocean glow",
    swatch: "linear-gradient(135deg, #0ea5e9, #06b6d4)",
    patch: {
      headerNavOnDark: "#f0f9ff",
      headerNavOnLight: "#0c4a6e",
      headerNavHoverColor: "#7dd3fc",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(14, 165, 233, 0.35)",
      headerBrandTextOnDark: "#f0f9ff",
      headerBrandSubtextOnDark: "rgba(186, 230, 253, 0.9)",
      headerBrandTextOnLight: "#0c4a6e",
      headerBrandSubtextOnLight: "rgba(12, 74, 110, 0.7)",
      headerCtaBg: "#0ea5e9",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#0284c7",
      headerCtaBorderColor: "#0ea5e9",
    },
  },
  {
    id: "royal-violet",
    label: "Royal violet",
    swatch: "linear-gradient(135deg, #6d28d9, #a78bfa)",
    patch: {
      headerNavOnDark: "#faf5ff",
      headerNavOnLight: "#4c1d95",
      headerNavHoverColor: "#ddd6fe",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(124, 58, 237, 0.4)",
      headerBrandTextOnDark: "#ffffff",
      headerBrandSubtextOnDark: "rgba(237, 233, 254, 0.9)",
      headerBrandTextOnLight: "#4c1d95",
      headerBrandSubtextOnLight: "rgba(76, 29, 149, 0.65)",
      headerCtaBg: "#7c3aed",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#6d28d9",
      headerCtaBorderColor: "#7c3aed",
    },
  },
  {
    id: "sunset-warm",
    label: "Sunset warm",
    swatch: "linear-gradient(135deg, #f97316, #fb7185)",
    patch: {
      headerNavOnDark: "#fff7ed",
      headerNavOnLight: "#9a3412",
      headerNavHoverColor: "#fed7aa",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(249, 115, 22, 0.38)",
      headerBrandTextOnDark: "#ffffff",
      headerBrandSubtextOnDark: "rgba(255, 237, 213, 0.92)",
      headerBrandTextOnLight: "#7c2d12",
      headerBrandSubtextOnLight: "rgba(124, 45, 18, 0.7)",
      headerCtaBg: "#ea580c",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#c2410c",
      headerCtaBorderColor: "#ea580c",
    },
  },
  {
    id: "emerald-luxe",
    label: "Emerald luxe",
    swatch: "linear-gradient(135deg, #059669, #34d399)",
    patch: {
      headerNavOnDark: "#ecfdf5",
      headerNavOnLight: "#064e3b",
      headerNavHoverColor: "#a7f3d0",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(16, 185, 129, 0.35)",
      headerBrandTextOnDark: "#ffffff",
      headerBrandSubtextOnDark: "rgba(209, 250, 229, 0.9)",
      headerBrandTextOnLight: "#065f46",
      headerBrandSubtextOnLight: "rgba(6, 95, 70, 0.68)",
      headerCtaBg: "#059669",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#047857",
      headerCtaBorderColor: "#059669",
    },
  },
  {
    id: "rose-chic",
    label: "Rose chic",
    swatch: "linear-gradient(135deg, #ec4899, #f472b6)",
    patch: {
      headerNavOnDark: "#fff1f2",
      headerNavOnLight: "#9d174d",
      headerNavHoverColor: "#fbcfe8",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(236, 72, 153, 0.35)",
      headerBrandTextOnDark: "#ffffff",
      headerBrandSubtextOnDark: "rgba(255, 228, 230, 0.92)",
      headerBrandTextOnLight: "#9f1239",
      headerBrandSubtextOnLight: "rgba(159, 18, 57, 0.68)",
      headerCtaBg: "#db2777",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#be185d",
      headerCtaBorderColor: "#db2777",
    },
  },
  {
    id: "light-pro",
    label: "Light bar pro",
    swatch: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    patch: {
      headerNavOnDark: "#1e293b",
      headerNavOnLight: "#0f172a",
      headerNavHoverColor: "#007cc3",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "#007cc3",
      headerBrandTextOnDark: "#0f172a",
      headerBrandSubtextOnDark: "rgba(51, 65, 85, 0.75)",
      headerBrandTextOnLight: "#0f172a",
      headerBrandSubtextOnLight: "rgba(71, 85, 105, 0.72)",
      headerCtaBg: "#007cc3",
      headerCtaColor: "#ffffff",
      headerCtaHoverBg: "#006aa8",
      headerCtaBorderColor: "#007cc3",
    },
  },
  {
    id: "champagne",
    label: "Champagne gold",
    swatch: "linear-gradient(135deg, #fef3c7, #fcd34d)",
    patch: {
      headerNavOnDark: "#422006",
      headerNavOnLight: "#78350f",
      headerNavHoverColor: "#b45309",
      headerNavActiveColor: "#ffffff",
      headerNavActiveBg: "rgba(180, 83, 9, 0.35)",
      headerBrandTextOnDark: "#422006",
      headerBrandSubtextOnDark: "rgba(120, 53, 15, 0.75)",
      headerBrandTextOnLight: "#78350f",
      headerBrandSubtextOnLight: "rgba(120, 53, 15, 0.68)",
      headerCtaBg: "#b45309",
      headerCtaColor: "#fffbeb",
      headerCtaHoverBg: "#92400e",
      headerCtaBorderColor: "#b45309",
    },
  },
];

/** Fields shown in Site Content (simple labels, no numbers) */
export const SITE_CONTENT_HEADER_COLOR_UI = [
  {
    id: "menu",
    label: "Menu links (Home, About, Services…)",
    fields: [
      { key: "headerNavOnDark", label: "Menu text (dark bar)", default: "#ffffff" },
      { key: "headerNavOnLight", label: "Menu text (light bar)", default: "#1a2b3c" },
      { key: "headerNavHoverColor", label: "Menu hover text", default: "#ffffff" },
      { key: "headerNavActiveColor", label: "Active menu text", default: "#ffffff" },
      { key: "headerNavActiveBg", label: "Active menu highlight", default: "rgba(0, 184, 169, 0.35)" },
    ],
  },
  {
    id: "brand",
    label: "Brand name (next to logo)",
    fields: [
      { key: "headerBrandTextOnDark", label: "Title on dark bar", default: "#ffffff" },
      { key: "headerBrandSubtextOnDark", label: "“Technologies” on dark bar", default: "rgba(255, 255, 255, 0.88)" },
      { key: "headerBrandTextOnLight", label: "Title on light bar", default: "#1a2b3c" },
      { key: "headerBrandSubtextOnLight", label: "“Technologies” on light bar", default: "rgba(26, 43, 60, 0.72)" },
    ],
  },
  {
    id: "cta",
    label: "Header button (Book Appointment)",
    fields: [
      { key: "headerCtaLabel", label: "Button text", default: "Book Appointment", type: "text" },
      { key: "headerCtaBg", label: "Button background", default: "#007cc3" },
      { key: "headerCtaColor", label: "Button label color", default: "#ffffff" },
      { key: "headerCtaHoverBg", label: "Button hover background", default: "#006aa8" },
    ],
  },
];
