import { resolveHeaderLogoFilter } from "./logoImageFilters";
import { resolveLogoUrls } from "./logoSettings";

/** Header design presets + CSS variables for live site and page builder preview */

export const HEADER_SIZES = {
  compact: { id: "compact", label: "Compact (64px)", height: 64, logoHeight: 52, navFont: 0.82 },
  default: { id: "default", label: "Standard (76px)", height: 76, logoHeight: 64, navFont: 0.92 },
  large: { id: "large", label: "Large (88px)", height: 88, logoHeight: 72, navFont: 1 },
};

export const HEADER_DESIGNS = {
  glass: {
    id: "glass",
    label: "Glass over hero (live home)",
    description: "Transparent blur bar on home & page heroes",
    swatch: "linear-gradient(135deg, rgba(10,22,40,0.7), rgba(0,61,92,0.5))",
    barBackground: "rgba(10, 22, 40, 0.55)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.12)",
  },
  gradient: {
    id: "gradient",
    label: "Purple → navy bar",
    description: "Solid gradient header strip",
    swatch: "linear-gradient(90deg, #2d1b4e, #003366)",
    barBackground: "linear-gradient(90deg, #2d1b4e 0%, #1a3a5c 45%, #003366 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#0099ff",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.1)",
  },
  solid: {
    id: "solid",
    label: "Solid navy",
    swatch: "#0a1628",
    barBackground: "#0a1628",
    barScrolled: "#ffffff",
    navOnDark: "#ffffff",
    navOnLight: "#0a1628",
    ctaBg: "#00b8a9",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.08)",
  },
  light: {
    id: "light",
    label: "Light bar",
    swatch: "linear-gradient(135deg, #ffffff, #f1f5f9)",
    barBackground: "linear-gradient(180deg, rgba(255, 255, 255, 0.98) 0%, rgba(248, 250, 252, 0.96) 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#1e293b",
    navOnLight: "#0f172a",
    ctaBg: "linear-gradient(135deg, #007cc3 0%, #0099cc 100%)",
    ctaColor: "#ffffff",
    border: "rgba(148, 163, 184, 0.25)",
  },
  ocean: {
    id: "ocean",
    label: "Ocean blue → teal",
    swatch: "linear-gradient(90deg, #0077b6, #00b4d8)",
    barBackground: "linear-gradient(90deg, #005f8a 0%, #0077b6 40%, #00b4d8 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#0a1628",
    ctaBg: "#00b4d8",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.15)",
  },
  sunset: {
    id: "sunset",
    label: "Sunset orange → coral",
    swatch: "linear-gradient(90deg, #ff6b35, #c73e1d)",
    barBackground: "linear-gradient(90deg, #ff6b35 0%, #f7931e 50%, #c73e1d 100%)",
    barScrolled: "rgba(255, 255, 255, 0.96)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#f7931e",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.2)",
  },
  midnight: {
    id: "midnight",
    label: "Midnight purple",
    swatch: "linear-gradient(180deg, #0f0c29, #302b63)",
    barBackground: "linear-gradient(125deg, #0f0c29 0%, #302b63 55%, #24243e 100%)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#7c3aed",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.1)",
  },
  emerald: {
    id: "emerald",
    label: "Emerald green",
    swatch: "linear-gradient(90deg, #064e3b, #10b981)",
    barBackground: "linear-gradient(90deg, #064e3b 0%, #059669 50%, #10b981 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#064e3b",
    ctaBg: "#059669",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.12)",
  },
  royal: {
    id: "royal",
    label: "Royal violet",
    swatch: "linear-gradient(90deg, #4c1d95, #7c3aed)",
    barBackground: "linear-gradient(90deg, #4c1d95 0%, #6d28d9 50%, #7c3aed 100%)",
    barScrolled: "rgba(255, 255, 255, 0.95)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#a78bfa",
    ctaColor: "#1e1b4b",
    border: "rgba(255, 255, 255, 0.14)",
  },
  slate: {
    id: "slate",
    label: "Slate gray",
    swatch: "linear-gradient(90deg, #334155, #64748b)",
    barBackground: "linear-gradient(90deg, #1e293b 0%, #334155 50%, #475569 100%)",
    barScrolled: "#f8fafc",
    navOnDark: "#f8fafc",
    navOnLight: "#0f172a",
    ctaBg: "#38bdf8",
    ctaColor: "#0f172a",
    border: "rgba(255, 255, 255, 0.1)",
  },
  cyber: {
    id: "cyber",
    label: "Cyber cyan glow",
    swatch: "linear-gradient(90deg, #0a1628, #00d4ff)",
    barBackground: "linear-gradient(90deg, #0a1628 0%, #003d5c 60%, #004d73 100%)",
    barScrolled: "rgba(10, 22, 40, 0.96)",
    navOnDark: "#00d4ff",
    navOnLight: "#0a1628",
    ctaBg: "#00d4ff",
    ctaColor: "#0a1628",
    border: "rgba(0, 212, 255, 0.35)",
  },
  rose: {
    id: "rose",
    label: "Rose wine",
    swatch: "linear-gradient(135deg, #881337, #ec4899)",
    barBackground: "linear-gradient(125deg, #881337 0%, #be185d 45%, #ec4899 100%)",
    barScrolled: "rgba(255, 255, 255, 0.95)",
    navOnDark: "#ffffff",
    navOnLight: "#881337",
    ctaBg: "#ec4899",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.15)",
  },
  arctic: {
    id: "arctic",
    label: "Arctic ice",
    swatch: "linear-gradient(135deg, #e0f2fe, #38bdf8, #7dd3fc)",
    barBackground: "linear-gradient(135deg, #f0f9ff 0%, #e0f2fe 40%, #bae6fd 75%, #7dd3fc 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#075985",
    navOnLight: "#0c4a6e",
    ctaBg: "#0284c7",
    ctaColor: "#ffffff",
    border: "rgba(56, 189, 248, 0.28)",
  },
  copper: {
    id: "copper",
    label: "Copper bronze",
    swatch: "linear-gradient(90deg, #78350f, #d97706)",
    barBackground: "linear-gradient(90deg, #78350f 0%, #b45309 50%, #d97706 100%)",
    barScrolled: "rgba(255, 255, 255, 0.96)",
    navOnDark: "#ffffff",
    navOnLight: "#78350f",
    ctaBg: "#d97706",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.18)",
  },
  /* —— MaatriDev site palette (20 more) —— */
  maatridevHome: {
    id: "maatridevHome",
    label: "Live IT hero (home)",
    swatch: "linear-gradient(125deg, #0a1628, #004d73)",
    barBackground: "linear-gradient(125deg, #0a1628 0%, #003d5c 55%, #004d73 100%)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.12)",
  },
  maatridevPage: {
    id: "maatridevPage",
    label: "Page banner blue",
    swatch: "linear-gradient(135deg, #007cc3, #003d5c)",
    barBackground: "linear-gradient(135deg, #007cc3 0%, #006aa8 40%, #003d5c 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.14)",
  },
  infosysTeal: {
    id: "infosysTeal",
    label: "Infosys blue → teal",
    swatch: "linear-gradient(90deg, #007cc3, #00b8a9)",
    barBackground: "linear-gradient(90deg, #007cc3 0%, #0099cc 45%, #00b8a9 100%)",
    barScrolled: "rgba(255, 255, 255, 0.95)",
    navOnDark: "#ffffff",
    navOnLight: "#0a1628",
    ctaBg: "#00b8a9",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.15)",
  },
  digitalAgency: {
    id: "digitalAgency",
    label: "Digital agency (purple→teal)",
    swatch: "linear-gradient(135deg, #2d1b4e, #00b8a9)",
    barBackground: "linear-gradient(135deg, #2d1b4e 0%, #1a3a5c 50%, #007cc3 75%, #00b8a9 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#00b8a9",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.12)",
  },
  webAgency: {
    id: "webAgency",
    label: "Web agency purple",
    swatch: "linear-gradient(90deg, #4c1d95, #2d1b4e)",
    barBackground: "linear-gradient(90deg, #4c1d95 0%, #2d1b4e 50%, #1a3a5c 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#2d1b4e",
    ctaBg: "#0099ff",
    ctaColor: "#ffffff",
    border: "rgba(167, 139, 250, 0.25)",
  },
  startupSlate: {
    id: "startupSlate",
    label: "Startup slate",
    swatch: "linear-gradient(90deg, #334155, #64748b)",
    barBackground: "linear-gradient(90deg, #1e293b 0%, #334155 60%, #475569 100%)",
    barScrolled: "#f8fafc",
    navOnDark: "#f8fafc",
    navOnLight: "#0f172a",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.1)",
  },
  tealAccent: {
    id: "tealAccent",
    label: "Navy + teal accent",
    swatch: "linear-gradient(90deg, #0a1628, #00b8a9)",
    barBackground: "linear-gradient(90deg, #0a1628 0%, #003d5c 70%, #00b8a9 100%)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#0a1628",
    ctaBg: "#00b8a9",
    ctaColor: "#ffffff",
    border: "rgba(0, 184, 169, 0.35)",
  },
  cyanCta: {
    id: "cyanCta",
    label: "Navy + cyan CTA",
    swatch: "linear-gradient(90deg, #0a1628, #0099ff)",
    barBackground: "linear-gradient(90deg, #0a1628 0%, #003366 55%, #004d73 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#0099ff",
    ctaColor: "#ffffff",
    border: "rgba(0, 153, 255, 0.3)",
  },
  deepPacific: {
    id: "deepPacific",
    label: "Deep pacific (#003d5c)",
    swatch: "linear-gradient(90deg, #003d5c, #004d73)",
    barBackground: "linear-gradient(90deg, #003d5c 0%, #004d73 50%, #007cc3 100%)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#003d5c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.1)",
  },
  frostedHero: {
    id: "frostedHero",
    label: "Frosted glass hero",
    swatch: "linear-gradient(135deg, rgba(10,22,40,0.85), rgba(0,61,92,0.6))",
    barBackground: "rgba(10, 22, 40, 0.42)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.18)",
  },
  brandRibbon: {
    id: "brandRibbon",
    label: "Brand ribbon (blue|teal)",
    swatch: "linear-gradient(90deg, #007cc3 50%, #00b8a9 50%)",
    barBackground: "linear-gradient(90deg, #007cc3 0%, #007cc3 48%, #00b8a9 52%, #00b8a9 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#ffffff",
    navOnLight: "#0a1628",
    ctaBg: "#006aa8",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.2)",
  },
  consultancy: {
    id: "consultancy",
    label: "Consultancy navy",
    swatch: "#0f2844",
    barBackground: "linear-gradient(90deg, #0f2844 0%, #0a1628 50%, #0c2238 100%)",
    barScrolled: "rgba(255, 255, 255, 0.96)",
    navOnDark: "#f4f8fc",
    navOnLight: "#0a1628",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.1)",
  },
  engagementBar: {
    id: "engagementBar",
    label: "Engagement purple-navy",
    swatch: "linear-gradient(90deg, #2d1b4e, #003366)",
    barBackground: "linear-gradient(90deg, #2d1b4e 0%, #1a3a5c 40%, #003366 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#0099ff",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.12)",
  },
  activeTeal: {
    id: "activeTeal",
    label: "Teal active nav",
    swatch: "linear-gradient(90deg, #0a1628, rgba(0,184,169,0.5))",
    barBackground: "linear-gradient(90deg, #0a1628 0%, #003d5c 100%)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#00b8a9",
    ctaColor: "#ffffff",
    border: "rgba(0, 184, 169, 0.45)",
  },
  mobileMenu: {
    id: "mobileMenu",
    label: "Mobile menu navy",
    swatch: "linear-gradient(165deg, #0f2844, #0a1628)",
    barBackground: "linear-gradient(165deg, #0f2844 0%, #0a1628 55%, #0c2238 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#f4f8fc",
    navOnLight: "#0a1628",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.08)",
  },
  cloudInner: {
    id: "cloudInner",
    label: "Inner page cloud",
    swatch: "linear-gradient(160deg, #f0f9ff, #e2e8f0, #cbd5e1)",
    barBackground: "linear-gradient(165deg, #f8fafc 0%, #f1f5f9 55%, #e2e8f0 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#1e293b",
    navOnLight: "#0f172a",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(100, 116, 139, 0.18)",
  },
  scheduleBlue: {
    id: "scheduleBlue",
    label: "Schedule consultation",
    swatch: "#007cc3",
    barBackground: "linear-gradient(90deg, #006aa8 0%, #007cc3 50%, #0099ff 100%)",
    barScrolled: "rgba(255, 255, 255, 0.95)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#0099ff",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.2)",
  },
  softGlass: {
    id: "softGlass",
    label: "Soft glass (services)",
    swatch: "linear-gradient(135deg, rgba(0,124,195,0.75), rgba(0,61,92,0.85))",
    barBackground: "rgba(10, 22, 40, 0.28)",
    barScrolled: "rgba(255, 255, 255, 0.92)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.14)",
  },
  indigoCorp: {
    id: "indigoCorp",
    label: "Corporate indigo",
    swatch: "linear-gradient(90deg, #1a3a5c, #003366)",
    barBackground: "linear-gradient(90deg, #1a3a5c 0%, #003366 60%, #0a1628 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(255, 255, 255, 0.1)",
  },
  innovationSpark: {
    id: "innovationSpark",
    label: "Innovation spark",
    swatch: "linear-gradient(90deg, #0a1628, #38bdf8, #00b8a9)",
    barBackground: "linear-gradient(90deg, #0a1628 0%, #003d5c 40%, #007cc3 70%, #00b8a9 100%)",
    barScrolled: "rgba(255, 255, 255, 0.94)",
    navOnDark: "#ffffff",
    navOnLight: "#0a1628",
    ctaBg: "#38bdf8",
    ctaColor: "#0a1628",
    border: "rgba(56, 189, 248, 0.35)",
  },
  mistLight: {
    id: "mistLight",
    label: "Mist light bar",
    swatch: "linear-gradient(135deg, #f8fafc, #e2e8f0)",
    barBackground: "linear-gradient(180deg, rgba(248, 250, 252, 0.99) 0%, rgba(241, 245, 249, 0.97) 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#334155",
    navOnLight: "#1e293b",
    ctaBg: "#00b8a9",
    ctaColor: "#ffffff",
    border: "rgba(148, 163, 184, 0.2)",
  },
  cream: {
    id: "cream",
    label: "Cream white",
    swatch: "#fffbeb",
    barBackground: "linear-gradient(90deg, #fffbeb 0%, #fef3c7 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#78350f",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(120, 53, 15, 0.12)",
  },
  linen: {
    id: "linen",
    label: "Linen off-white",
    swatch: "#fafaf9",
    barBackground: "rgba(250, 250, 249, 0.98)",
    barScrolled: "#ffffff",
    navOnDark: "#334155",
    navOnLight: "#0f172a",
    ctaBg: "#0ea5e9",
    ctaColor: "#ffffff",
    border: "rgba(15, 23, 42, 0.08)",
  },
  snow: {
    id: "snow",
    label: "Pure snow white",
    swatch: "#ffffff",
    barBackground: "#ffffff",
    barScrolled: "#ffffff",
    navOnDark: "#0f172a",
    navOnLight: "#0f172a",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(15, 23, 42, 0.08)",
  },
  skyWash: {
    id: "skyWash",
    label: "Sky wash blue",
    swatch: "#eff6ff",
    barBackground: "linear-gradient(90deg, #eff6ff 0%, #dbeafe 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#1e3a8a",
    navOnLight: "#1e3a8a",
    ctaBg: "#2563eb",
    ctaColor: "#ffffff",
    border: "rgba(37, 99, 235, 0.15)",
  },
  pearl: {
    id: "pearl",
    label: "Pearl (MD mist)",
    swatch: "#f4f8fc",
    barBackground: "rgba(244, 248, 252, 0.98)",
    barScrolled: "#ffffff",
    navOnDark: "#1a2b3c",
    navOnLight: "#1a2b3c",
    ctaBg: "#007cc3",
    ctaColor: "#ffffff",
    border: "rgba(0, 124, 195, 0.1)",
  },
  sage: {
    id: "sage",
    label: "Sage mint",
    swatch: "#ecfdf5",
    barBackground: "linear-gradient(90deg, #ecfdf5 0%, #d1fae5 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#065f46",
    navOnLight: "#065f46",
    ctaBg: "#059669",
    ctaColor: "#ffffff",
    border: "rgba(5, 150, 105, 0.15)",
  },
  blush: {
    id: "blush",
    label: "Blush pink",
    swatch: "#fdf2f8",
    barBackground: "linear-gradient(90deg, #fdf2f8 0%, #fce7f3 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#9d174d",
    navOnLight: "#9d174d",
    ctaBg: "#db2777",
    ctaColor: "#ffffff",
    border: "rgba(219, 39, 119, 0.12)",
  },
  sand: {
    id: "sand",
    label: "Warm sand",
    swatch: "#fef9c3",
    barBackground: "linear-gradient(90deg, #fefce8 0%, #fef9c3 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#854d0e",
    navOnLight: "#854d0e",
    ctaBg: "#d97706",
    ctaColor: "#ffffff",
    border: "rgba(133, 77, 14, 0.12)",
  },
  mintFrost: {
    id: "mintFrost",
    label: "Mint frost",
    swatch: "#f0fdfa",
    barBackground: "linear-gradient(90deg, #f0fdfa 0%, #ccfbf1 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#115e59",
    navOnLight: "#115e59",
    ctaBg: "#0d9488",
    ctaColor: "#ffffff",
    border: "rgba(13, 148, 136, 0.15)",
  },
  roseMist: {
    id: "roseMist",
    label: "Rose mist",
    swatch: "#fff1f2",
    barBackground: "linear-gradient(90deg, #fff1f2 0%, #ffe4e6 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#9f1239",
    navOnLight: "#9f1239",
    ctaBg: "#e11d48",
    ctaColor: "#ffffff",
    border: "rgba(225, 29, 72, 0.12)",
  },
  warmIvory: {
    id: "warmIvory",
    label: "Warm ivory",
    swatch: "linear-gradient(135deg, #fff7ed, #fed7aa)",
    barBackground: "linear-gradient(135deg, #fffbeb 0%, #fff7ed 45%, #ffedd5 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#7c2d12",
    navOnLight: "#9a3412",
    ctaBg: "#ea580c",
    ctaColor: "#ffffff",
    border: "rgba(251, 146, 60, 0.22)",
  },
  aurora: {
    id: "aurora",
    label: "Aurora pastel",
    swatch: "linear-gradient(135deg, #e0e7ff, #fce7f3, #cffafe)",
    barBackground: "linear-gradient(125deg, #eef2ff 0%, #fae8ff 42%, #ecfeff 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#4338ca",
    navOnLight: "#5b21b6",
    ctaBg: "#6366f1",
    ctaColor: "#ffffff",
    border: "rgba(99, 102, 241, 0.2)",
  },
  champagne: {
    id: "champagne",
    label: "Champagne gold",
    swatch: "linear-gradient(135deg, #fef9c3, #fde68a, #fcd34d)",
    barBackground: "linear-gradient(135deg, #fffbeb 0%, #fef3c7 50%, #fde68a 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#78350f",
    navOnLight: "#92400e",
    ctaBg: "#b45309",
    ctaColor: "#fffbeb",
    border: "rgba(245, 158, 11, 0.28)",
  },
  lagoon: {
    id: "lagoon",
    label: "Lagoon turquoise",
    swatch: "linear-gradient(135deg, #ccfbf1, #5eead4, #2dd4bf)",
    barBackground: "linear-gradient(135deg, #f0fdfa 0%, #ccfbf1 45%, #99f6e4 100%)",
    barScrolled: "#ffffff",
    navOnDark: "#0f766e",
    navOnLight: "#115e59",
    ctaBg: "#14b8a6",
    ctaColor: "#ffffff",
    border: "rgba(20, 184, 166, 0.25)",
  },
};

const LIGHT_BAR_BG_HINTS = [
  "#fff",
  "ffffff",
  "f8fafc",
  "f4f7fb",
  "f4f8fc",
  "f0f9ff",
  "eff6ff",
  "fafaf9",
  "fffbeb",
  "fef3c7",
  "e0f2fe",
  "bae6fd",
  "ecfdf5",
  "fdf2f8",
  "fef9c3",
  "fefce8",
  "f0fdfa",
  "fff1f2",
  "fff7ed",
  "ffedd5",
  "mist",
  "cream",
  "linen",
  "snow",
  "pearl",
  "sage",
  "blush",
  "sand",
  "arctic",
  "cloud",
  "aurora",
  "lagoon",
  "champagne",
  "eef2ff",
  "fae8ff",
  "ecfeff",
  "fde68a",
  "99f6e4",
];

function navIsDarkOnLightBar(navOnDark = "") {
  const n = String(navOnDark).trim().toLowerCase();
  if (!n || n === "#ffffff" || n === "#fff" || n === "white") return false;
  if (n.includes("255, 255, 255") || n.includes("244, 248, 252") || n.includes("248, 250, 252")) {
    return false;
  }
  return true;
}

function barBackgroundIsLight(barBackground = "") {
  const b = String(barBackground).toLowerCase();
  return LIGHT_BAR_BG_HINTS.some((hint) => b.includes(hint));
}

/** Light bar = pale background + dark menu text (for colored logos) */
export function isLightHeaderDesign(design) {
  if (!design) return false;
  return navIsDarkOnLightBar(design.navOnDark) && barBackgroundIsLight(design.barBackground);
}

const LIGHT_HEADER_DISPLAY_ORDER = [
  "aurora",
  "lagoon",
  "champagne",
  "arctic",
  "light",
  "snow",
  "pearl",
  "mistLight",
  "cloudInner",
  "skyWash",
  "sage",
  "mintFrost",
  "blush",
  "roseMist",
  "linen",
  "cream",
  "sand",
  "warmIvory",
];

/** All light header designs in HEADER_DESIGNS (not a fixed count) */
export const HEADER_LIGHT_DESIGN_IDS = [
  ...LIGHT_HEADER_DISPLAY_ORDER.filter((id) => isLightHeaderDesign(HEADER_DESIGNS[id])),
  ...Object.values(HEADER_DESIGNS)
    .filter((d) => isLightHeaderDesign(d) && !LIGHT_HEADER_DISPLAY_ORDER.includes(d.id))
    .map((d) => d.id)
    .sort((a, b) => a.localeCompare(b)),
];

export const HEADER_DARK_QUICK_IDS = ["glass", "maatridevHome", "solid", "infosysTeal", "maatridevPage"];

export function headerQuickPresets(ids) {
  return ids.map((id) => {
    const d = HEADER_DESIGNS[id];
    return {
      id,
      label: d?.label || id,
      swatch: d?.swatch,
      patch: () => applyHeaderDesignPreset(id),
    };
  });
}

/** One-click combos matching live site screenshots */
export const HEADER_THEME_PRESETS = [
  {
    id: "live-home",
    label: "Live home (glass)",
    description: "Transparent bar on teal hero — matches public homepage",
    patch: () => ({
      ...applyHeaderDesignPreset("glass"),
      headerCtaLabel: "Book Appointment",
      headerCtaBg: "#007cc3",
      headerSize: "default",
    }),
  },
  {
    id: "purple-bar",
    label: "Purple gradient bar",
    patch: () => ({
      ...applyHeaderDesignPreset("gradient"),
      headerCtaLabel: "Schedule Consultation",
      headerCtaBg: "#0099ff",
      headerSize: "default",
    }),
  },
  {
    id: "page-hero",
    label: "About / Services banner",
    patch: () => ({
      ...applyHeaderDesignPreset("glass"),
      headerBarOverHero: "rgba(10, 22, 40, 0.2)",
      headerNavOnDark: "#ffffff",
      headerCtaLabel: "Book Appointment",
      headerCtaBg: "#007cc3",
    }),
  },
  { id: "ocean-bar", label: "Ocean gradient", patch: () => applyHeaderDesignPreset("ocean") },
  { id: "sunset-bar", label: "Sunset gradient", patch: () => applyHeaderDesignPreset("sunset") },
  { id: "midnight-bar", label: "Midnight purple", patch: () => applyHeaderDesignPreset("midnight") },
  { id: "emerald-bar", label: "Emerald green", patch: () => applyHeaderDesignPreset("emerald") },
  { id: "royal-bar", label: "Royal violet", patch: () => applyHeaderDesignPreset("royal") },
  { id: "cyber-bar", label: "Cyber cyan", patch: () => applyHeaderDesignPreset("cyber") },
  { id: "rose-bar", label: "Rose wine", patch: () => applyHeaderDesignPreset("rose") },
  { id: "arctic-bar", label: "Arctic ice", patch: () => applyHeaderDesignPreset("arctic") },
  { id: "light-bar", label: "Light white bar", patch: () => applyHeaderDesignPreset("light") },
  { id: "snow-bar", label: "Snow white", patch: () => applyHeaderDesignPreset("snow") },
  { id: "cloud-bar", label: "Cloud inner", patch: () => applyHeaderDesignPreset("cloudInner") },
  { id: "sage-bar", label: "Sage mint", patch: () => applyHeaderDesignPreset("sage") },
  { id: "pearl-bar", label: "Pearl mist", patch: () => applyHeaderDesignPreset("pearl") },
  { id: "copper-bar", label: "Copper bronze", patch: () => applyHeaderDesignPreset("copper") },
  { id: "slate-bar", label: "Slate pro", patch: () => applyHeaderDesignPreset("slate") },
  { id: "md-home", label: "★ Live IT hero", patch: () => applyHeaderDesignPreset("maatridevHome") },
  { id: "md-page", label: "★ Page banner", patch: () => applyHeaderDesignPreset("maatridevPage") },
  { id: "md-brand", label: "★ Blue→teal brand", patch: () => applyHeaderDesignPreset("infosysTeal") },
  { id: "md-digital", label: "★ Digital agency", patch: () => applyHeaderDesignPreset("digitalAgency") },
  { id: "md-web", label: "Web agency", patch: () => applyHeaderDesignPreset("webAgency") },
  { id: "md-startup", label: "Startup slate", patch: () => applyHeaderDesignPreset("startupSlate") },
  { id: "md-teal", label: "Teal accent", patch: () => applyHeaderDesignPreset("tealAccent") },
  { id: "md-cyan", label: "Cyan CTA bar", patch: () => applyHeaderDesignPreset("cyanCta") },
  { id: "md-pacific", label: "Deep pacific", patch: () => applyHeaderDesignPreset("deepPacific") },
  { id: "md-frosted", label: "Frosted glass", patch: () => applyHeaderDesignPreset("frostedHero") },
  { id: "md-ribbon", label: "Brand ribbon", patch: () => applyHeaderDesignPreset("brandRibbon") },
  { id: "md-consult", label: "Consultancy", patch: () => applyHeaderDesignPreset("consultancy") },
  { id: "md-engage", label: "Engagement bar", patch: () => applyHeaderDesignPreset("engagementBar") },
  { id: "md-active", label: "Teal active nav", patch: () => applyHeaderDesignPreset("activeTeal") },
  { id: "md-mobile", label: "Mobile menu navy", patch: () => applyHeaderDesignPreset("mobileMenu") },
  { id: "md-cloud", label: "Inner cloud", patch: () => applyHeaderDesignPreset("cloudInner") },
  { id: "md-schedule", label: "Schedule blue", patch: () => applyHeaderDesignPreset("scheduleBlue") },
  { id: "md-soft", label: "Soft glass", patch: () => applyHeaderDesignPreset("softGlass") },
  { id: "md-indigo", label: "Corporate indigo", patch: () => applyHeaderDesignPreset("indigoCorp") },
  { id: "md-spark", label: "Innovation spark", patch: () => applyHeaderDesignPreset("innovationSpark") },
  { id: "md-mist", label: "Mist light", patch: () => applyHeaderDesignPreset("mistLight") },
];

export function applyHeaderDesignPreset(designId) {
  const d = HEADER_DESIGNS[designId] || HEADER_DESIGNS.glass;
  return {
    headerDesign: d.id,
    headerBarBackground: d.barBackground,
    headerBarOverHero: d.barBackground,
    headerBarScrolled: d.barScrolled,
    headerNavOnDark: d.navOnDark,
    headerNavOnLight: d.navOnLight,
    headerCtaBg: d.ctaBg,
    headerCtaColor: d.ctaColor,
  };
}

export function previewContextFromPath(pathname = "/") {
  if (pathname === "/" || pathname.startsWith("/home/")) return "home";
  const pageHeroRoots = [
    "/about",
    "/services",
    "/contact",
    "/team",
    "/projects",
    "/blog",
    "/pricing",
    "/appointment",
    "/engagement",
  ];
  if (pageHeroRoots.some((p) => pathname === p || pathname.startsWith(`${p}/`))) return "pageHero";
  return "inner";
}

export function resolveHeaderTheme(settings = {}, opts = {}) {
  const {
    editorPreview = false,
    scrolled = false,
    onDarkBackdrop = false,
    previewContext = "home",
  } = opts;
  const design = HEADER_DESIGNS[settings.headerDesign] || HEADER_DESIGNS.glass;
  const size = HEADER_SIZES[settings.headerSize] || HEADER_SIZES.default;

  const barBg = settings.headerBarBackground || design.barBackground;
  const barOverHero = settings.headerBarOverHero || design.barBackground;
  const barLight = settings.headerBarScrolled || design.barScrolled;

  const useDarkStyle = editorPreview ? previewContext !== "inner" : onDarkBackdrop;

  let glassBg = barBg;
  if (editorPreview) {
    glassBg = previewContext === "home" || previewContext === "pageHero" ? barOverHero : barBg;
  } else if (scrolled) {
    glassBg = barLight;
  } else if (previewContext === "home" || previewContext === "pageHero") {
    glassBg = barOverHero;
  } else {
    glassBg = barBg;
  }

  const navColor =
    scrolled && !editorPreview
      ? settings.headerNavOnLight || design.navOnLight
      : settings.headerNavOnDark || design.navOnDark;

  const logos = resolveLogoUrls(settings, useDarkStyle);
  const logoSrc = logos.display;

  return {
    design,
    size,
    logoSrc,
    previewContext,
    cssVars: {
      "--header-height": `${size.height}px`,
      "--header-logo-height": `${size.logoHeight}px`,
      "--header-nav-font": `${size.navFont}rem`,
      "--header-glass-bg": glassBg,
      "--header-glass-dark": barBg,
      "--header-glass-light": barLight,
      "--header-glass-hero": barOverHero,
      "--header-nav-color": navColor,
      "--header-nav-dark": settings.headerNavOnDark || design.navOnDark,
      "--header-nav-light": settings.headerNavOnLight || design.navOnLight,
      "--header-nav-active": settings.headerNavActiveColor || "#ffffff",
      "--header-nav-active-bg": settings.headerNavActiveBg || "rgba(0, 184, 169, 0.35)",
      "--header-nav-hover": settings.headerNavHoverColor || settings.headerNavOnDark || "#ffffff",
      "--header-nav-hover-bg": settings.headerNavHoverBg || "rgba(255, 255, 255, 0.12)",
      "--header-brand-on-dark": settings.headerBrandTextOnDark || "#ffffff",
      "--header-brand-sub-on-dark": settings.headerBrandSubtextOnDark || "rgba(255, 255, 255, 0.88)",
      "--header-brand-on-light": settings.headerBrandTextOnLight || settings.headerNavOnLight || "#1a2b3c",
      "--header-brand-sub-on-light":
        settings.headerBrandSubtextOnLight || "rgba(26, 43, 60, 0.72)",
      "--header-border": settings.headerBarBorderColor || design.border,
      "--header-bar-shadow": settings.headerBarShadowColor || "rgba(0, 40, 80, 0.08)",
      "--header-dropdown-bg": settings.headerDropdownBg || "rgba(255, 255, 255, 0.96)",
      "--header-dropdown-text": settings.headerDropdownText || "#1a2b3c",
      "--header-dropdown-hover-bg": settings.headerDropdownHoverBg || "#f4f7fb",
      "--header-cta-bg": settings.headerCtaBg || design.ctaBg,
      "--header-cta-color": settings.headerCtaColor || design.ctaColor,
      "--header-cta-hover-bg": settings.headerCtaHoverBg || "#006aa8",
      "--header-cta-border": settings.headerCtaBorderColor || settings.headerCtaBg || design.ctaBg,
      "--header-toggle-bg": settings.headerToggleBg || "rgba(255, 255, 255, 0.1)",
      "--header-toggle-border": settings.headerToggleBorderColor || "rgba(255, 255, 255, 0.25)",
      "--header-toggle-icon": settings.headerToggleIconColor || "#ffffff",
      "--header-logo-filter": resolveHeaderLogoFilter(settings),
      "--header-logo-primary": settings.logoColorPrimary || "#007cc3",
      "--header-logo-accent": settings.logoColorAccent || "#00b8a9",
      "--logo-scale": settings.logoScale ?? 1,
      "--logo-clip-width": `${settings.logoClipWidth ?? 300}px`,
    },
    useDarkStyle,
  };
}
